# Generated by Django 3.2.12 on 2022-06-26 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerinfomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('firstname', models.CharField(max_length=50, verbose_name='first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phonenumber', models.IntegerField(unique=True, verbose_name='phone number')),
                ('location', models.CharField(max_length=300, verbose_name='location')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='afternoonmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_typea', models.CharField(max_length=100)),
                ('pricea', models.CharField(max_length=20)),
                ('descriptiona', models.TextField(default='', max_length=100)),
                ('createda', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 1, 645630))),
            ],
        ),
        migrations.CreateModel(
            name='eveningmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_types', models.CharField(max_length=100)),
                ('prices', models.CharField(max_length=20)),
                ('descriptions', models.TextField(default='', max_length=100)),
                ('createds', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 1, 645630))),
            ],
        ),
        migrations.CreateModel(
            name='morningmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('description', models.TextField(default='', max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 1, 644630))),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='orderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 1, 646630))),
                ('order', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='foodapp.morningmenu')),
            ],
        ),
    ]
