# Generated by Django 3.2.12 on 2022-06-26 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoonmenu',
            name='createda',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 12, 874303)),
        ),
        migrations.AlterField(
            model_name='eveningmenu',
            name='createds',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 12, 875302)),
        ),
        migrations.AlterField(
            model_name='morningmenu',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 12, 873303)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 3, 12, 875302)),
        ),
    ]
